# variables related to AWS
aws:
  # AWS region
  region: 
  # AWS access key for user
  access_key: 
  # AWS secret key for user
  secret_key: 

# variables related to databricks
databricks:
  # databricks account id
  account_id: 
  # databricks server principle (for IAC API calls) client id
  client_id: 
  # databricks server principle (for IAC API calls) client secret
  client_secret: 
  # name of the workspace to be provisioned in databricks
  workspace_name: 

# S3 bucket names
s3_storage:
  # unique name for the main data processing storage bucket. For example "pintereset-batch-storage-processing-bucket"
  main_processing_data_storage_name: 
  # unique name for the storage for databricks workspace. For example "pinterest-databricks-root-bucket"
  databricks_root_storage_name: 
  # unique name for the aiflow dag storage bucket. For example "pinterest-dag"
  mwaa_dag_storage_name: 

# mwaa environment
mwaa:
  # mwaa environment name. Make sure the words for the name is separated with '-'. For example "mwaa-env", not "mwaa_env"
  mwaa_env_name: 